//
//  InvidiousChannel.swift
//  
//
//  Created on 07/05/2021
//


import Foundation

struct InvidiousChannel: Codable {
    
    struct RelatedChannel: Codable {
        let author: String
        let authorId: String
        let authorUrl: String
        let authorThumbnails: [InvidiousAuthorThumbnail]
    }
    
    struct SearchResult: Codable {
        let author: String
        let authorId: String
        let authorUrl: String
        let authorThumbnails: [InvidiousAuthorThumbnail]
        
        let subCount: Int32
        let videoCount: Int64
        let description: String
        let descriptionHtml: String
    }
    
    let author: String
    let authorId: String
    let authorUrl: String
    let authorBanners: [InvidiousAuthorBanner]
    let authorThumbnails: [InvidiousAuthorThumbnail]
    let error: String?
    
    let subCount: Int32
    let totalViews: Int64
    let joined: Int64
    
    let paid: Bool
    let autoGenerated: Bool
    let isFamilyFriendly: Bool
    let description: String
    let descriptionHtml: String
    let allowedRegions: [String]
    
    let latestVideos: [InvidiousVideoPreview.ChannelVideo]
    let relatedChannels: [Self.RelatedChannel]
    
}

